# Learning NumPy Fundamentals

In this notebook I took structured notes and examples while learning more about NumPy and do numerous excercises to show what I've learned. I use various resources including Codecademy and geeksforgeeks.  

## NumPy Arrays Introduction

NumPy Arrays are a data structure akin to a special type of list. Unlike python lists, NumPy arrays generally store elements using a single data type ('dtype'), including strings, numbers, or even other arrays.

## NumPy Mathematical Operations

NumPy arrays are most powerful when the items in an array are numbers as NumPy arrays can have powerful mathematical operations performed on them.

In [3]:
import numpy as np
# NumPy arrays appear similar to normal lists
my_list = [1, 2, 3, 4, 5, 6]
my_array = np.array([1, 2, 3, 4, 5, 6])

# lists can be converted to NumPy arrays too
my_converted_array = np.array(my_list)

print(f'List: {my_list}, NumPy Array: {my_array}, List converted to array: {my_converted_array}')

List: [1, 2, 3, 4, 5, 6], NumPy Array: [1 2 3 4 5 6], List converted to array: [1 2 3 4 5 6]


For example theres mathematical operations such as mean, maximum, sum, minimum

In [4]:
# From geeksforgeeks
n = np.array([9, 3, 3, 5])
# Mean used to get the average value across the elements in an array
print(f'Mean of the elements in the array is: {n.mean()}')
# Sum is used to calculate the sum of array elements along a specified axis or across all axes
array = np.array([[10, 17, 25], [15, 11, 22]])
result_axis0 = np.sum(array, axis=0)
result_axis1 = np.sum(array, axis=1)
result_axisNoneGiven = np.sum(array)
print(f'Sum of each column element: {result_axis0}') # Output: [25 28 47]
print(f'Sum of each row: {result_axis1}') # Output: [52 48]
print(f'Sum of every element in array: {result_axisNoneGiven}')
# maximum is used to compare and return the element wise maximum values
a = np.array([2, 8, 125])
b = np.array([3, 3, 15])
print(f'maximum is: {np.maximum(a, b)}')
# minimum is used for opposite
print(f'Minimum is: {np.minimum(a, b)}')

Mean of the elements in the array is: 5.0
Sum of each column element: [25 28 47]
Sum of each row: [52 48]
Sum of every element in array: 100
maximum is: [  3   8 125]
Minimum is: [ 2  3 15]


In [5]:
# 2D array
A = np.array([[1, 2],
             [3, 4]])
res = np.dot(A, A) # Matrix multiplication
print("Dot multiplication")
print(res)

# Another way of doing dot multiplication:
resbest = A @ A
print(resbest) # Notice same result

# Addition
B = np.array([[5, 7], [7, 8]])
print("Addition")
print(A + B)

Dot multiplication
[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]
Addition
[[ 6  9]
 [10 12]]


## Random Module

NumPy also has a random module which gives functions for generating random numbers

In [6]:
import numpy as np

a = np.random.normal(0, 1, 5)    # 5 values from normal distribution
print("Data:", a)
print("Mean:", np.mean(a))

Data: [ 2.45010827  0.75748655 -0.08561697 -0.33958716  0.42679194]
Mean: 0.6418365265526356


## Combining NumPy Arrays

One can build 2D arrays by combining 1D arrays

In [7]:
import numpy as np

l1 = [1, 2, 3, 4]
l2 = [5, 6, 7, 8]
l3 = [9, 10, 11, 12]
arr = np.array([l1, l2, l3])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## NumPy Array Parameters

NumPy arrays have various parameters.

1. Axis represents a dimension of an array
- Axis 0 -> Rows (first dimension)
- Axis 1 -> Columns (second dimension)
- Axis 2 -> Third dimension in a 3D array

Eg.) a two dimensional array has axis 0 and axis 1.

Eg 2.)
`arr.mean(axis=0)` averages down the rows and returns one value per column
`arr.mean(axis=1)` averages across the columns and returns one value per row

2. Shape indicates the # of elements along each dimension. It is returned as a tuple.


In [8]:
import numpy as np
arr = np.array([ [0, 4, 2],
                 [3, 4, 5],
                 [23, 4, 5],
                 [2, 34, 5],
                 [5, 6, 7] ])
print(arr.shape) # prints row, column as a tuple

(5, 3)


3. Rank it is the number of dimensions (axes) it has
- Eg one dimensional array has rank 1, two dimensional array has rank 2, etc.

In [9]:
print(np.array([1, 2, 3]).ndim)      # Rank 1
print(np.array([[1, 2], [3, 4]]).ndim)  # Rank 2

1
2


4. Datatype (dtype) is the property which specifies the type of data stored in an array

In [10]:
import numpy as np

arr1 = np.array([[0, 4, 2]])
arr2 = np.array([0.2, 0.4, 2.4])

print("Data type of array 1:", arr1.dtype)
print("Data type of array 2:", arr2.dtype)

Data type of array 1: int64
Data type of array 2: float64


## Special NumPy Initialization

Also can initialize a Python NumPy Array using Special Functions:
- np.zeros(): Creates an array filled with zeros.
- np.ones(): Creates an array filled with ones.
- np.full(): Creates an array filled with a specified value.
- np.arange(): Creates an array with values that are evenly spaced within a given range.
- np.linspace(): Creates an array with values that are evenly spaced over a specified interval.


## More about Random module

Can also create a python numpy array using random number generation too (good for creating new weight arrays?)
- np.random.rand(): Creates an array of specified shape and fills it with random values sampled from a uniform distribution over [0, 1).
- np.random.randn(): Creates an array of specified shape and fills it with random values sampled from a standard normal distribution.
- np.random.randint(): Creates an array of specified shape and fills it with random integers within a given range.

In [11]:
import numpy as np

ar = np.random.rand(2, 3)
an = np.random.randn(2, 2)
ai = np.random.randint(1, 11, size=(2, 3)) # Creates an array of size (2, 3) using numbers 1-10 inclusive

print(ar)
print(an)
print(ai)

[[0.07440755 0.91158735 0.94946015]
 [0.96411422 0.40648856 0.28825054]]
[[-0.14330716 -0.54280786]
 [ 0.98188664 -0.26645578]]
[[7 3 2]
 [5 5 8]]


## Matrix Creation Routines

Can create Python Numpy Arrays using Matrix Creation Routines:
- np.eye(): Creates an identity matrix of specified size.
- np.diag(): Constructs a diagonal array.
- np.zeros_like(): Creates an array of zeros with the same shape and type as a given array.
- np.ones_like(): Creates an array of ones with the same shape and type as a given array.

In [12]:
import numpy as np

im = np.eye(3)
da = np.diag([1, 2, 3])
a0 = np.zeros_like(da)
a1 = np.ones_like(da)

print(im)
print(da)
print(a0)
print(a1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


## NumPy Array Indexing

Numpy Array indexing is very similar to list indexing.

In [13]:
# From GeeksForGeeks
# Accessing elements in 1D arrays
arr = np.array([10, 20, 30, 40, 50])
print(arr[0]) # Access first item in list

10


In [14]:
# Accessing elements in 2D arrays
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[1, 2]) # Second row (1), and third item (2) Row then column, row then column.

# Theres another way of doing it
print(matrix[1][2]) # Second row (1), and third item (2)

6
6


In [15]:
# 3D arrays need 3 indices:
# - Depth: Specifies the 2D slice
# - Row: Specifies the row within the slice
# - Column: Specifies the column within the row
cube = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],

                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])

print(cube[1, 2, 0])

16


## Array Slicing

Can also access specific rows using what is known as slicing

In [16]:
# From GeeksForGeeks
# Slicing start at first number, and go UP TO but NOT INCLUDING the second number
import numpy as np

arr = np.array([[10, 20, 30], [40, 5, 66], [70, 88, 94]])
print("Array:")
print(arr)

res = arr[[0,2]]
print("Accessed Rows :")
print(res)

Array:
[[10 20 30]
 [40  5 66]
 [70 88 94]]
Accessed Rows :
[[10 20 30]
 [70 88 94]]


In [17]:
# Accessing the middle row of 2D NumPy array
arr = np.array([[101, 20, 3, 10], [40, 5, 66, 7], [70, 88, 9, 141]])
print("Array:")
print(arr)

res = arr[1]
print("Accessed Row :")
print(res)

Array:
[[101  20   3  10]
 [ 40   5  66   7]
 [ 70  88   9 141]]
Accessed Row :
[40  5 66  7]


In [18]:
# Getting first 2 rows, first 2 columns
arr = np.array([[12, 15, 18],
                [25, 30, 35],
                [40, 45, 50]])
print("Array:")
print(arr)

res = arr[:2, :2]  # Up to 2, but not including.
print("Accessed Elements:")
print(res)

# Theres further info about 3D arrays, inquire further here:
# https://www.geeksforgeeks.org/python/how-to-access-different-rows-of-a-multidimensional-numpy-array/

Array:
[[12 15 18]
 [25 30 35]
 [40 45 50]]
Accessed Elements:
[[12 15]
 [25 30]]


## Boolean Masks

Another part of arrays is using Boolean masks. Boolean masks allow for selecting specific elements from a NumPy array based on a True/False condition.

In [19]:
# Taken from https://www.plus2net.com/python/numpy-boolean-masks.php
x = np.array([5, 12, 7, 22, 3, 18, 17])
maskedArray = x[x >= 10]
print(maskedArray)

# Can be done using combined conditions
maskedArray2 = x[(x >= 10) & (x % 2 == 0)]
print(maskedArray2)

[12 22 18 17]
[12 22 18]


Also can do masking for 2D arrays

In [20]:
# Taken from https://www.plus2net.com/python/numpy-boolean-masks.php
b = np.array([[ 1,  2,  3],
              [10, 20, 30],
              [40, 50, 60]])

# Column-wise filter: take rows where column 0 >= 10
row_mask = b[:, 0] >= 10
print(b[row_mask])      # [[10 20 30],
                        #  [40 50 60]]

# Element-wise mask: keep only elements >= 20
elem_mask = b >= 20
print(b[elem_mask])     # [20 30 40 50 60]

[[10 20 30]
 [40 50 60]]
[20 30 40 50 60]


## Conditional Replace with where()

Conditional replace with np.where (np.where(cond, a_if_true, a_if_false) )

In [21]:
# Replace values < 10 with 0, keep others
y = np.where(x < 10, 0, x)
print(y)  # [ 0 12  0 22  0 18]

[ 0 12  0 22  0 18 17]


## NumPy Array Broadcasting.
Broadcasting in NumPy allows us to perform arithmetic operations on arrays of different shapes without reshaping them.

In [22]:
a = np.array([[1, 2, 3], [4, 5, 6]])
x = 10
print(a + x)
# NumPy expands the scalar x to match the shape of array a
# The operation a + x then adds 10 to each element of a

[[11 12 13]
 [14 15 16]]


In [23]:
# This includes multiplication
fd = np.array([ [0.8, 2.9, 3.9],
                [52.4, 23.6, 36.5],
                [55.2, 31.7, 23.9],
                [14.4, 11.0, 4.9] ])

cpg = np.array([9, 4, 4])
res = fd * cpg
print(res)
# cpg broadcasts across each row of fd

[[  7.2  11.6  15.6]
 [471.6  94.4 146. ]
 [496.8 126.8  95.6]
 [129.6  44.   19.6]]


In [24]:
# Can broadcast/correct across vertical columns not just rows
import numpy as np

temp = np.array([ [30, 32, 34, 33, 31],
                  [25, 27, 29, 28, 26],
                  [20, 22, 24, 23, 21] ])

corr = np.array([1.5, -0.5, 2.0])
res = temp + corr[:, None]
print(res)

[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]


Can also broadcast a 1D array to a 2D array

In [25]:
a = np.array([2, 4, 6])
b = np.array([[1, 3, 5], [7, 9, 11]])
res = a + b
print(res)
# Here NumPy automatically reshapes a to the same shape as b in order to perform the addition (2, 3)

[[ 3  7 11]
 [ 9 13 17]]


Can also broadcast in conditional operators too

In [26]:
a = np.array([12, 24, 35, 45, 60, 72])
b = np.array(["Adult", "Minor"])
res = np.where(a > 18, b[0], b[1]) # Condition, array element to add if true, array element to add otherwise
# Ages > 18 creates a boolean array by checking every value at once (broadcasting)
# np.where() picks "Adult" for true, and "Minor" for False without any loop!
# Result is an array labeling each age correctly
print(res)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


## Normalization and Broadcasting

Broadcasting can be used for simplifying normalization.

Normalization is important to machine learning because it:
- Centers data by subtracting the mean by ensuring features have zero mean
- Scales data by dividing by the standard deviation by ensuring features have unit variance (assuming the feature has nonzero variance, if column is constant then standard deviation is 0 and one cannot simply divide by zero...)
- Improves numerical stability and performance of algorithms like gradient descent (numerical stability simply meaning that calculations behave reliably when performed by a computer, aka floating point numbers have finite percision, so working with smaller numbers (but not too small) rather than extremely large ones ensures better accuracy during training ml models) (as well standardization ensures gradient descent is faster/easier as the optimization landscape is much better scaled)

In [27]:
img = np.array([ [100, 120, 130],
                 [90, 110, 140],
                 [80, 100, 120] ])
# Think of each column of the array as a "feature"
# The rows are samples

m = img.mean(axis=0) # Gets the mean for each feature (column) [90, 120, 130]
s = img.std(axis=0) # Gets the standard deviation
res = (img - m) / s # Ensures features have unit variance and centers the data
# (img - m) specifically changes each feature such that mean = 0, negative is below avg, pos is above avg
# dividing by standard deviation changes units to # of standard deviations from avergae
print(res)
# m and s are 1D arrays, but despite this NumPy broadcasts them across all rows of img
# (img - m) centers the data, and you can subtract a (3,3) shape (img) from m (3,) despite them being different shapes
# because of broadcasting.
# Dividing by s scales it, giving the standardized values (z-scores)

[[ 1.22474487  1.22474487  0.        ]
 [ 0.          0.          1.22474487]
 [-1.22474487 -1.22474487 -1.22474487]]


The mean of [160, 170, 180] is (160 + 170 + 180) / 3 = 170. To achieve zero mean, we subtract the mean from each value of the array. So zero mean data is now [-10, 0, +10]. It's called zero mean because its mean will always be 0 (-10 + 0 + 10 / 3 = 0).  
- Zero mean data means that for each element (such as +10) it indicates just how far from the mean value each original element was. Eg.) 170 is +10 from mean. The zero mean data can also be graphed to show variance, aka how spread out the values are from around the mean
- Unit variance means variance = 1. When you divide the zero mean data by the standard deviation, you rescale the feature such that: mean = 0, variance = 1, std = 1. This is called standardization.
- The result of standardization is an array of numbers that answer by how many standard deviations away from average is the value. Eg.) -2 means 2 standard deviations below average, 0 means exactly average, and 2 means standard deviations above average.
- Wrote this block based on AI explanations

The importance of standardization is that it scales the values to be important/more relevant to ML algorithms. E.g. a sample of data may contain:
- age = 25
- income = 85000
- children = 2
These values are greatly different in quantity, as such an ML may be heavily affected by 85,000 simply due to its large quantity (can disproportionately affect distance based methods and optimization behavior). but of course despite its large value it isn't 3400x more important than age despite it being that much larger. Standardization fixes this issue, after which observe:
- age = -1.1
- Income = +0.4
- children = -0.3
As such all features now exist at comparable scales and have meaningful interpretations:
- 1.1 standard deviations younger than average
- 0.4 standard deviations above average income
- 0.3 standard deviations below average number of children


- Wrote this block based on AI explanations

## Vectorization
Vectorization in NumPy refers to applying operations on entire arrays without using explicit loops. These operations are internally optimized using fast C/C++ implementations, making numerical computations more efficient and easier to write. (https://www.geeksforgeeks.org/numpy/vectorized-operations-in-numpy/)

In [28]:
# https://www.geeksforgeeks.org/numpy/vectorized-operations-in-numpy/
# Adding numbers to each element without loops
import numpy as np

a1 = np.array([2, 4, 6, 8, 10])
num = 2
res = a1 + num
print(res)

[ 4  6  8 10 12]


In [29]:
# Adding arrays element wise

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
res = a1 + a2
print(res)

[5 7 9]


In [30]:
# Element wise scalar multiplication
a1 = np.array([1, 2, 3, 4])
res = a1 * 2
print(res)

[2 4 6 8]


In [31]:
# Logic operations on arrays
a1 = np.array([10, 20, 30])
res = a1 > 15
print(res)

[False  True  True]


In [39]:
# np.vectorize can make a scalar Python function operate element-by-element,
# but it does not provide the same performance benefits as native NumPy operations.

vec = np.vectorize(lambda x: x**2 + 2*x + 1)
res = vec(a1)

# Preferred native NumPy version:
res_native = a1**2 + 2*a1 + 1

In [33]:
# As geeksforgeeks notes, these vectorized operations not only take less code to
# write, but also the operations take less time too
import time

arr = np.arange(1_000_000)

# Loop
t1 = time.time()
loop_res = [x * 2 for x in arr]
t2 = time.time()

# Vectorized
t3 = time.time()
vec_res = arr * 2
t4 = time.time()

print("Loop Time:", t2 - t1)
print("Vectorized Time:", t4 - t3)

Loop Time: 0.16013526916503906
Vectorized Time: 0.003717660903930664


## Reshaping

Reshaping is used to modify the dimensions of an existing array without changing its data

In [34]:
# From https://www.geeksforgeeks.org/python/reshape-numpy-array/
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
r = a.reshape(2, 3) # Auto converts to this shape!
print(r)

[[1 2 3]
 [4 5 6]]


In [35]:
# Another example which creates a 3-D array from 1-D array
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
r = a.reshape(2, 2, 2)
print(r)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
# -1 is a special case of reshaping that can be used for calculating the needed
# dimension automatically
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
r = a.reshape(3, -1) # Calculates that the needed dimension is 4~!
print(r)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Key Takeaways

After completing these notes, I am comfortable with:

- Creating and inspecting NumPy arrays
- Reasoning about shapes and axes
- Indexing and slicing multidimensional arrays
- Filtering data with boolean masks
- Using broadcasting and vectorized operations
- Standardizing numerical features
- Performing matrix multiplication
- Reshaping arrays for different computational tasks