# NumPy Fundamentals Project

This project demonstrates core NumPy skills through analysis of a simulated student grade dataset. It covers array creation, indexing, slicing, aggregation, masking, broadcasting, vectorization, standardization, reshaping, and matrix operations

## Self performed Excercise (No internet /chatgpt help)
Task: Imagine you are given data from 100 students across 5 assessments. Your job is to generate and analyze the dataset using NumPy only.

## Part 1: Create the dataset



Use numpy to randomly generate a (100, 5) array containing integer grades from 40-100 then print shape, number of dimensions, and datatype

## Part 2: Basic statistics

Use numpy to calculate:
- avg grade across dataset
- highest grade
- lowest grade
- average grade for each assessment
- average grade for each student
- standard deviation for each assessment

## Part 3: Indexing and slicing

Extract:
- All grades belonging to the first 10 students
- Grades for assessment #3 only
- Grades for first 10 students on the first 3 assessments
- The grade belonging to student #25 on assessment #4

## Part 4: Boolean Masking

Find:
- Every individual grade >= 90
- How many individual grades are >= 90
- All students whose avg grade is >= 80
- All students whose avg grade is < 60

## Part 5: Conditional replacement

Create a new array where:
- grades < 50 become 0
- everything else remains unchanged
using np.where()

Then verify original dataset is unchanged

## Part 6

Give assessments different weights
Suppose the assessments are weighted:
weights = np.array([0.10, 0.15, 0.20, 0.25, 0.30])

- Calculate the weighted final grade of every student without using any python loops. Result should have shape (100,)

## Part 7

Standardize each assessment independently so that each column approximately has mean = 0 and std = 1

Prove the standardization worked by calculating the mean and std of the std columns

## Part 8

Imagine the school decides to give everyone 5 bonus points, but grades cannot exceed 100. Create the updated dataset without a loop

E.g.)
- 96 → 100
- 82 → 87
- 100 → 100
- 47 → 52

## Part 9

Take the first 20 students and reshape their data from (20, 5) into (10, 10) and then reshape back to (20, 5). Verify that the restored data is identical to the original first 20 students

## Part 10: Final challenge

Produce a summary like:
NUMPY STUDENT PERFORMANCE REPORT

Students: 100
Assessments: 5

Overall mean: XX.XX
Highest grade: XX
Lowest grade: XX

Assessment means:
[XX.XX XX.XX XX.XX XX.XX XX.XX]

Students with average >= 80: XX
Students with average < 60: XX

Highest weighted final grade: XX.XX
Lowest weighted final grade: XX.XX

However do all this without python for loops

In [1]:
# Part 1: Create the dataset
# Use numpy to randomly generate a (100, 5) array containing integer grades from
#  40-100 then print shape, number of dimensions, and datatype

# Used notes: random
import numpy as np
# grades_array = np.random.randint(1, 10, size=(2, 3))
np.random.seed(42)
grades_array = np.random.randint(40, 101, size=(100, 5)) # IMPORTANT: 101 NOT 100!!

print(grades_array)
print(grades_array.shape) # Print shape
print(grades_array.ndim) # Print number dimensions
print(grades_array.dtype) # print data type



[[ 78  91  68  54  82]
 [ 47 100  60  78  97]
 [ 58  62  50  50  63]
 [ 92  75  79  63  42]
 [ 61  92  41  63  83]
 [ 69  77  41  99  60]
 [ 72  51  97  61 100]
 [ 83  64  88  66  98]
 [ 81  67  99  55  54]
 [ 86  90  83  94  91]
 [ 96  42  76  90  46]
 [ 60  48  78  57  43]
 [ 64  99  53  89  97]
 [ 48  65  92  41  59]
 [ 67  86  99  46  83]
 [100  47  86  74  53]
 [ 56  75  89  79  43]
 [ 41  45  93  81  43]
 [ 93  68  57  65  83]
 [ 73  49  75  53  70]
 [ 87  54  47  53  62]
 [ 99  96  79  60  55]
 [ 84  57  86  92  63]
 [ 65  64  99  99  99]
 [ 84  80  68  54  84]
 [ 40  64  46  48  63]
 [ 40  83  47  63  50]
 [ 90  56  47  74  74]
 [ 72  98  44  81  78]
 [ 97  80  67  46  48]
 [ 47  51  73  72  87]
 [ 94  62  63  76  74]
 [ 83  79  61  66  74]
 [ 40  74  76  86  53]
 [ 42  40  44  65  94]
 [ 53  78  66  48  54]
 [ 54  65  81  99  52]
 [ 90  71  78  88  91]
 [100  71  43  69  76]
 [ 62  78  84  54  82]
 [ 68  75  52  71  46]
 [ 98  90  61  67  41]
 [ 81  84  96  92  45]
 [ 67  67  

In [2]:
# part 2: Basic statistics

# No notes used

# Calculate avg grade across the entire dataset
print(grades_array.mean())

# print highest grade
print(grades_array.max())

# print lowest grade
print(grades_array.min())

# print avg grade for each assessment (column)
print(grades_array.mean(axis=0))

# print avg grade for each student (rows)
print(grades_array.mean(axis=1))

# Print std for each assessment
print(grades_array.std(axis=0))

70.784
100
40
[69.73 71.5  72.06 70.18 70.45]
[74.6 76.4 56.6 70.2 68.  69.2 76.2 79.8 71.2 88.8 70.  57.2 80.4 61.
 76.2 72.  68.4 60.6 73.2 64.  60.6 77.8 76.4 85.2 74.  52.2 56.6 68.2
 74.6 67.6 66.  73.8 72.6 65.8 57.  59.8 70.2 83.6 71.8 72.  62.4 71.4
 79.6 71.8 75.4 70.  77.  55.6 73.4 78.2 75.2 83.  65.  85.  60.8 63.4
 70.4 69.4 75.2 63.2 65.  69.  73.2 59.6 69.4 73.  63.4 74.2 67.8 92.2
 52.6 77.4 70.8 70.4 72.8 67.4 72.6 61.6 80.4 63.  69.6 60.6 78.8 73.8
 76.  68.  73.6 72.4 72.6 72.8 77.2 81.8 84.4 60.8 81.  71.6 64.2 61.8
 74.8 81.6]
[17.83808005 16.44658019 17.5743108  18.23479092 17.60930152]


In [3]:
# Part 3: Indexing and slicing

# No notes were used

# Extract all grades belonging to the first 10 students
# Aka get first 10 rows of data (slicing)
print(f'first 10 rows:\n {grades_array[:10]}')

# Extract grades for assessment #3 only
print(f'get grades for 3rd assessment:\n {grades_array[:,2]}')

# Extract grades for first 10 students on the first 3 assessments
# Get first 10 rows of data, and first 3 columns
print(f'Get grades for first 10 students on the first 3 assessments:\n {grades_array[:10,:3]}')

# Get the grade belonging to student # 25 on assessment #4
print(f'Get the grade belonging to student # 25 on assessment #4:\n {grades_array[24,3]}')



first 10 rows:
 [[ 78  91  68  54  82]
 [ 47 100  60  78  97]
 [ 58  62  50  50  63]
 [ 92  75  79  63  42]
 [ 61  92  41  63  83]
 [ 69  77  41  99  60]
 [ 72  51  97  61 100]
 [ 83  64  88  66  98]
 [ 81  67  99  55  54]
 [ 86  90  83  94  91]]
get grades for 3rd assessment:
 [68 60 50 79 41 41 97 88 99 83 76 78 53 92 99 86 89 93 57 75 47 79 86 99
 68 46 47 47 44 67 73 63 61 76 44 66 81 78 43 84 52 61 96 83 97 72 91 45
 72 54 63 97 42 56 67 72 83 94 98 91 87 98 59 65 46 78 67 70 99 91 87 98
 58 63 91 77 64 85 55 43 59 56 90 69 93 60 72 58 83 92 76 92 91 72 70 85
 61 41 48 68]
Get grades for first 10 students on the first 3 assessments:
 [[ 78  91  68]
 [ 47 100  60]
 [ 58  62  50]
 [ 92  75  79]
 [ 61  92  41]
 [ 69  77  41]
 [ 72  51  97]
 [ 83  64  88]
 [ 81  67  99]
 [ 86  90  83]]
Get the grade belonging to student # 25 on assessment #4:
 54


In [4]:
# Part 4: Boolean masking

# Used no notes

# Find every individual grade >= 90
# uses boolean masking
print(f'Every individual grade over 90:\n {grades_array[grades_array >= 90]}')

# Find how many individual grades are >= 90
# uses boolean masking + len()
print(f'The number of grades over 90: {len(grades_array[grades_array >= 90])}')

# Find all students whose avg grades are >= 80 (should contain complete rows of grades + avgs)
l1 = grades_array[grades_array.mean(axis=1) >= 80] # avg grades above 80
# average across columns (assessments) producing one avg per student
print(f'All students scores whose avg grades are >= 80:\n {l1}')

# Find all students whose avg grade is < 60
l2 = grades_array[grades_array.mean(axis=1) < 60] # avg grades below 60
print(f'All students scores whose avg grades are < 60:\n {l2}')


Every individual grade over 90:
 [ 91 100  97  92  92  99  97 100  98  99  90  94  91  96  90  99  97  92
  99 100  93  93  99  96  92  99  99  99  90  98  97  94  94  99  90  91
 100  98  90  96  92  97  94  96  96  91  90  98  93  91  97  91  95  98
  93  92  94  94  95  98  91  99  98  99  98  91  96  99  96  91  99  98
  94  93  95  91  93 100  95  98  90  94  90  93  99 100  92  99  92  99
  91 100  93  97  93  94]
The number of grades over 90: 96
All students scores whose avg grades are >= 80:
 [[ 86  90  83  94  91]
 [ 64  99  53  89  97]
 [ 65  64  99  99  99]
 [ 90  71  78  88  91]
 [ 88  88  97  91  51]
 [ 88  95  56  98  88]
 [ 87  96  91  99  88]
 [ 93  74  55 100  80]
 [ 88  85  92  70  74]
 [ 99  72  91 100  60]
 [ 64  81  70  93  97]
 [ 87  78  68  81  94]]
All students scores whose avg grades are < 60:
 [[58 62 50 50 63]
 [60 48 78 57 43]
 [40 64 46 48 63]
 [40 83 47 63 50]
 [42 40 44 65 94]
 [53 78 66 48 54]
 [42 78 45 47 66]
 [75 58 65 42 58]
 [41 40 87 51 44]]


In [5]:
# Part 5: Conditional Replacement

# No notes were used

# Create a new array where:
# - grades < 50 become 0
# - everything else remains unchanged
# Use np.where
drop_scores_array = np.where(grades_array < 50, 0, grades_array)

print(f'New array:\n {drop_scores_array}')

# Verify that original array remains unchanged
print(f'Original data:\n {grades_array}')

New array:
 [[ 78  91  68  54  82]
 [  0 100  60  78  97]
 [ 58  62  50  50  63]
 [ 92  75  79  63   0]
 [ 61  92   0  63  83]
 [ 69  77   0  99  60]
 [ 72  51  97  61 100]
 [ 83  64  88  66  98]
 [ 81  67  99  55  54]
 [ 86  90  83  94  91]
 [ 96   0  76  90   0]
 [ 60   0  78  57   0]
 [ 64  99  53  89  97]
 [  0  65  92   0  59]
 [ 67  86  99   0  83]
 [100   0  86  74  53]
 [ 56  75  89  79   0]
 [  0   0  93  81   0]
 [ 93  68  57  65  83]
 [ 73   0  75  53  70]
 [ 87  54   0  53  62]
 [ 99  96  79  60  55]
 [ 84  57  86  92  63]
 [ 65  64  99  99  99]
 [ 84  80  68  54  84]
 [  0  64   0   0  63]
 [  0  83   0  63  50]
 [ 90  56   0  74  74]
 [ 72  98   0  81  78]
 [ 97  80  67   0   0]
 [  0  51  73  72  87]
 [ 94  62  63  76  74]
 [ 83  79  61  66  74]
 [  0  74  76  86  53]
 [  0   0   0  65  94]
 [ 53  78  66   0  54]
 [ 54  65  81  99  52]
 [ 90  71  78  88  91]
 [100  71   0  69  76]
 [ 62  78  84  54  82]
 [ 68  75  52  71   0]
 [ 98  90  61  67   0]
 [ 81  84  96  92   0]

In [6]:
# Part 6: Give assessments different weights

# No notes were used to complete question

# The assessments are weighted:
weights = np.array([0.10, 0.15, 0.20, 0.25, 0.30])

# calculate the weighted final grade of every student without a python loop
# End result should have shape: (100,)

# Multiply each row by the weights and add them together (dot product!?)
weighted_array = grades_array @ weights

print(f"Verifying shape is correct: {weighted_array.shape}")

print(f"Final grades: {weighted_array}")

Verifying shape is correct: (100,)
Final grades: [73.15 80.3  56.5  64.6  68.75 69.4  79.5  81.4  67.9  89.5  67.4  55.95
 83.2  60.9  75.8  68.65 67.3  62.6  72.05 63.9  58.05 71.6  76.05 90.35
 72.7  53.7  56.6  67.5  74.35 61.   71.05 72.5  71.05 67.7  63.45 58.4
 71.7  84.55 69.3  72.8  60.   64.55 76.4  71.8  77.4  71.3  76.2  56.45
 77.4  80.95 77.65 79.45 67.15 85.15 65.5  60.05 72.05 72.9  75.95 62.85
 66.35 67.   79.05 57.1  72.5  72.6  68.1  73.75 67.35 92.45 53.45 75.75
 68.95 77.4  73.75 68.8  70.95 58.9  80.4  60.8  68.7  66.2  81.25 75.
 72.05 68.4  74.7  67.6  71.25 71.4  73.25 79.65 81.9  58.4  84.9  75.5
 60.   60.   76.7  82.45]


In [7]:
# Part 7: Standarizing the dataset

# No notes used

# standardize each assessment independently so that each column (axis 0) approximately has:
# - mean = 0
# - standard deviation 1
# z = (x - mean) / std

mean = grades_array.mean(axis = 0)
stn_dev = grades_array.std(axis = 0)

standard_array_part1 = (grades_array - mean) / stn_dev

# Check that the standardization worked such that each column has mean 0 and std 1
print(f'Means:\n {standard_array_part1.mean(axis = 0)}') # Floating point close to 0
print(f'Standard Deviations:\n {standard_array_part1.std(axis = 0)}')


Means:
 [-1.97619698e-16 -2.77555756e-18 -1.40720768e-16 -3.85247390e-16
 -1.68753900e-16]
Standard Deviations:
 [1. 1. 1. 1. 1.]


In [8]:
# Part 8: Vectorization Challenge

# No notes used

# Now imagine the school decides to give everyone 5 bonus points, but grades cannot exceed 100
grade_inflation_raw = grades_array + 5

# np.where() can be used to replace any grades above 100 with 100 if need be
grade_inflation = np.where(grade_inflation_raw > 100, 100, grade_inflation_raw)

print(f'grades before 5 bonus points:\n {grades_array}')
print(f'grades after 5 bonus points:\n {grade_inflation}')

# Checking if any grades are above 100 (Should be an empty array)
print(f'Grades higher than 100:\n {grade_inflation[grade_inflation > 100]}')

grades before 5 bonus points:
 [[ 78  91  68  54  82]
 [ 47 100  60  78  97]
 [ 58  62  50  50  63]
 [ 92  75  79  63  42]
 [ 61  92  41  63  83]
 [ 69  77  41  99  60]
 [ 72  51  97  61 100]
 [ 83  64  88  66  98]
 [ 81  67  99  55  54]
 [ 86  90  83  94  91]
 [ 96  42  76  90  46]
 [ 60  48  78  57  43]
 [ 64  99  53  89  97]
 [ 48  65  92  41  59]
 [ 67  86  99  46  83]
 [100  47  86  74  53]
 [ 56  75  89  79  43]
 [ 41  45  93  81  43]
 [ 93  68  57  65  83]
 [ 73  49  75  53  70]
 [ 87  54  47  53  62]
 [ 99  96  79  60  55]
 [ 84  57  86  92  63]
 [ 65  64  99  99  99]
 [ 84  80  68  54  84]
 [ 40  64  46  48  63]
 [ 40  83  47  63  50]
 [ 90  56  47  74  74]
 [ 72  98  44  81  78]
 [ 97  80  67  46  48]
 [ 47  51  73  72  87]
 [ 94  62  63  76  74]
 [ 83  79  61  66  74]
 [ 40  74  76  86  53]
 [ 42  40  44  65  94]
 [ 53  78  66  48  54]
 [ 54  65  81  99  52]
 [ 90  71  78  88  91]
 [100  71  43  69  76]
 [ 62  78  84  54  82]
 [ 68  75  52  71  46]
 [ 98  90  61  67  41]
 [ 

In [9]:
# Part 9: Reshaping

# used notes for reshape syntax

# Bonus: figure out how -1 could be used in one of those reshapes
# Take the first 20 students and reshape their data from (20, 5) into (10, 10)
reshape_array = grades_array[:20]
reshape_array = np.reshape(reshape_array, (10, 10))
print(f'Compact (10, 10):\n{reshape_array}')
# Then reshape it back into (20, 5)
reshape_array = np.reshape(reshape_array, (20, -1))
print(f'Back to original shape:\n{reshape_array}')



Compact (10, 10):
[[ 78  91  68  54  82  47 100  60  78  97]
 [ 58  62  50  50  63  92  75  79  63  42]
 [ 61  92  41  63  83  69  77  41  99  60]
 [ 72  51  97  61 100  83  64  88  66  98]
 [ 81  67  99  55  54  86  90  83  94  91]
 [ 96  42  76  90  46  60  48  78  57  43]
 [ 64  99  53  89  97  48  65  92  41  59]
 [ 67  86  99  46  83 100  47  86  74  53]
 [ 56  75  89  79  43  41  45  93  81  43]
 [ 93  68  57  65  83  73  49  75  53  70]]
Back to original shape:
[[ 78  91  68  54  82]
 [ 47 100  60  78  97]
 [ 58  62  50  50  63]
 [ 92  75  79  63  42]
 [ 61  92  41  63  83]
 [ 69  77  41  99  60]
 [ 72  51  97  61 100]
 [ 83  64  88  66  98]
 [ 81  67  99  55  54]
 [ 86  90  83  94  91]
 [ 96  42  76  90  46]
 [ 60  48  78  57  43]
 [ 64  99  53  89  97]
 [ 48  65  92  41  59]
 [ 67  86  99  46  83]
 [100  47  86  74  53]
 [ 56  75  89  79  43]
 [ 41  45  93  81  43]
 [ 93  68  57  65  83]
 [ 73  49  75  53  70]]


In [10]:
# Part 10: Final challenge no loop summary

# No notes were used

print("NUMPY STUDENT PERFORMANCE REPORT\n")
print(f'# of students: {len(grades_array)}')
print(f'Assessments: {len(grades_array[0])}\n')

print(f'Overall mean: {grades_array.mean()}')
print(f'Highest grade: {grades_array.max()}')
print(f'Lowest grade: {grades_array.min()}\n')

print(f'Assessment means:\n{grades_array.mean(axis=0)}\n')
print(f'# of students with average >= 80: {len(grades_array[grades_array.mean(axis = 1) >= 80])}')
print(f'# of students with average < 60: {len(grades_array[grades_array.mean(axis = 1) < 60])}\n')

print(f'Highest weighted final grade: {weighted_array.max()}')
print(f'Lowest weighted final grade: {weighted_array.min()}')

NUMPY STUDENT PERFORMANCE REPORT

# of students: 100
Assessments: 5

Overall mean: 70.784
Highest grade: 100
Lowest grade: 40

Assessment means:
[69.73 71.5  72.06 70.18 70.45]

# of students with average >= 80: 12
# of students with average < 60: 9

Highest weighted final grade: 92.45
Lowest weighted final grade: 53.45


## What I Learned

This project helped reinforce how NumPy operations work across different
axes and how boolean masking, broadcasting, and vectorization can replace
many operations that would otherwise require Python loops.

The most important concepts I practiced were reasoning about array shapes,
performing operations along specific axes, and using matrix operations for
weighted calculations.